# Generated by Django 5.0 on 2023-12-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="users",
            field=models.ManyToManyField(
                related_name="users", to="split_free_all.user"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payer",
                to="split_free_all.user",
            ),
        ),
    ]
