# Generated by Django 4.2 on 2024-01-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0009_alter_member_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="group",
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True, null=True, to="split_free_all.member"
            ),
        ),
    ]
