# Generated by Django 4.2 on 2024-01-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0010_remove_member_group_alter_group_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="split_free_all.group",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="group_members",
                to="split_free_all.member",
            ),
        ),
    ]
