# Generated by Django 4.2 on 2024-01-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0011_member_group_alter_group_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.AlterField(
            model_name="member",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="split_free_all.group",
            ),
        ),
    ]
