# Generated by Django 4.2 on 2024-01-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0014_balance_currency_debt_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="split_free_all.member",
            ),
        ),
    ]
