# Generated by Django 4.2 on 2024-02-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0020_invitetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="split_free_all.group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="example@hotmail.com", max_length=128, null=True, unique=True
            ),
        ),
    ]
