# Generated by Django 4.2 on 2024-02-19 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0021_user_is_anonymous_alter_member_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=256)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="split_free_all.group",
                    ),
                ),
            ],
        ),
    ]
