# Generated by Django 4.2 on 2024-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0026_alter_expense_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.CharField(default="", max_length=240),
        ),
    ]
