# Generated by Django 4.2 on 2024-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0028_user_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
