# Generated by Django 4.2 on 2024-03-09 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0029_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
