# Generated by Django 4.2 on 2024-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split_free_all", "0030_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
