# Use a base image suitable for development
FROM python:3.10

# Install system dependencies
RUN apt-get update && apt-get install -y netcat-traditional
RUN ln -sf /bin/nc.traditional /bin/nc

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install development dependencies
RUN mkdir requirements
COPY requirements/base.txt requirements
COPY requirements/dev.txt requirements
RUN pip install --upgrade pip && pip install -r requirements/dev.txt

# Collect static files
RUN python manage.py collectstatic --noinput

# Copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Copy the Django project files into the container
COPY . .

# Run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
