# Use a base image suitable for development
FROM python:3.10

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install development dependencies
RUN pip install --upgrade pip
COPY requirements requirements
RUN pip install --upgrade pip && pip install -r requirements/dev.txt

# Copy the Django project files into the container
COPY . .

# Expose port 8000 for the Django development server
EXPOSE 8000

# Command to run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
