FROM python:3.10-slim

WORKDIR /app

COPY requirements requirements
RUN pip install -r requirements/staging.txt

COPY . .

RUN python manage.py makemigrations
RUN python manage.py migrate

RUN python manage.py collectstatic --noinput
