# Generated by Django 5.0 on 2023-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_expense_users_alter_expense_payer"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
