# Generated by Django 4.2 on 2023-12-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_idealtransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrower",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=255)),
                ("description", models.TextField()),
                ("members", models.ManyToManyField(to="core.user")),
            ],
        ),
        migrations.RemoveField(
            model_name="idealtransfer",
            name="event",
        ),
        migrations.RemoveField(
            model_name="idealtransfer",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="idealtransfer",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="usereventdebt",
            name="event",
        ),
        migrations.RemoveField(
            model_name="usereventdebt",
            name="user",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="users",
            new_name="participants",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="event",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="IdealTransfer",
        ),
        migrations.DeleteModel(
            name="UserEventDebt",
        ),
        migrations.AddField(
            model_name="debt",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="lender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lender",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user"),
        ),
        migrations.AddField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.group",
            ),
        ),
    ]
