# Generated by Django 4.2 on 2024-01-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_expense_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="user",
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(default="EUR", max_length=4),
        ),
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="balance",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.member",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrower",
                to="core.member",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="lender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lender",
                to="core.member",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(related_name="participants", to="core.member"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payer",
                to="core.member",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(blank=True, null=True, to="core.member"),
        ),
    ]
