# Generated by Django 4.2 on 2024-01-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_group_members_alter_member_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payer",
                to="core.member",
            ),
        ),
    ]
