# Generated by Django 4.2 on 2024-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_expense_payer"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish lira"),
                ],
                default="EUR",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish lira"),
                ],
                default="EUR",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish lira"),
                ],
                default="EUR",
                max_length=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("name", "group")},
        ),
    ]
