# Generated by Django 4.2 on 2024-02-03 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0017_alter_user_managers_user_groups_user_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(related_name="expense_groups", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="debt",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts_borrowed",
                to="core.member",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="lender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts_lent",
                to="core.member",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(related_name="participated_expenses", to="core.member"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payed_expenses",
                to="core.member",
            ),
        ),
    ]
