# Generated by Django 4.2 on 2024-02-03 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0018_group_creator_group_users_alter_debt_borrower_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(null=True, related_name="expense_groups", to=settings.AUTH_USER_MODEL),
        ),
    ]
