# Generated by Django 4.2 on 2024-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_activity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
