# Generated by Django 4.2 on 2024-03-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
