# Generated by Django 4.2 on 2024-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
